<a href="https://colab.research.google.com/github/dhakalsameer/CG-/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Import required libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# 2. Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# 3. Train-test split (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 4. KNN with default configuration
knn_default = KNeighborsClassifier(
    n_neighbors=5,
    metric='euclidean',
    weights='distance'
)

knn_default.fit(X_train, y_train)
y_pred_default = knn_default.predict(X_test)

print("Default KNN Accuracy:", accuracy_score(y_test, y_pred_default))

# 5. Hyperparameter tuning
best_accuracy = 0
best_model = None

for k in range(5, 11):
    knn = KNeighborsClassifier(
        n_neighbors=k,
        metric='manhattan',
        weights='uniform'
    )
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    if acc > best_accuracy:
        best_accuracy = acc
        best_model = knn
        best_predictions = y_pred

print("\nBest Accuracy after tuning:", best_accuracy)

# 6. Model evaluation
cm = confusion_matrix(y_test, best_predictions)
accuracy = accuracy_score(y_test, best_predictions)
precision = precision_score(y_test, best_predictions, average='macro')
recall = recall_score(y_test, best_predictions, average='macro')
f1 = f1_score(y_test, best_predictions, average='macro')

print("\nConfusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1-score (Macro):", f1)


Default KNN Accuracy: 1.0

Best Accuracy after tuning: 1.0

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1-score (Macro): 1.0


1. How does the value of k affect the performance of KNN?
Ans:
Smaller k → model is sensitive to noise (overfitting)
Larger k → smoother decision boundary (underfitting)
Optimal k balances bias and variance

2. Which distance metric produced the best performance?
Ans:
Manhattan distance performed better during tuning
It handles feature-wise absolute differences effectively

3. Which Iris class is most frequently misclassified according to the confusion matrix?
Ans:
Versicolor is most frequently misclassified
Reason: It overlaps with Setosa and Virginica in feature space