<a href="https://colab.research.google.com/github/dhakalsameer/CG-/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split into training (70%) and testing (30%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)


# Default Decision Tree model
dt_default = DecisionTreeClassifier(
    criterion="gini",
    max_depth=None,
    min_samples_split=2,
    random_state=42
)

dt_default.fit(X_train, y_train)
y_pred_default = dt_default.predict(X_test)

print("Default Model Accuracy:",
      accuracy_score(y_test, y_pred_default))


best_accuracy = 0
best_model = None
best_params = None

max_depth_values = [2, 3, 4, 5]
criteria = ["gini", "entropy"]
min_samples_split_values = [2, 4]

for depth in max_depth_values:
    for crit in criteria:
        for min_split in min_samples_split_values:

            model = DecisionTreeClassifier(
                max_depth=depth,
                criterion=crit,
                min_samples_split=min_split,
                random_state=42
            )

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            acc = accuracy_score(y_test, y_pred)

            if acc > best_accuracy:
                best_accuracy = acc
                best_model = model
                best_predictions = y_pred
                best_params = (depth, crit, min_split)

print("\nBest Model Parameters:")
print("Max Depth:", best_params[0])
print("Criterion:", best_params[1])
print("Min Samples Split:", best_params[2])
print("Best Accuracy:", best_accuracy)


# Confusion Matrix
cm = confusion_matrix(y_test, best_predictions)

# Metrics
accuracy = accuracy_score(y_test, best_predictions)
precision = precision_score(y_test, best_predictions, average="macro")
recall = recall_score(y_test, best_predictions, average="macro")
f1 = f1_score(y_test, best_predictions, average="macro")

print("\nConfusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1-score (Macro):", f1)


Default Model Accuracy: 1.0

Best Model Parameters:
Max Depth: 3
Criterion: gini
Min Samples Split: 2
Best Accuracy: 1.0

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1-score (Macro): 1.0


1. How does the maximum depth affect the performance of the Decision Tree?
Ans:
Small depth → underfitting (model too simple)
Large depth → overfitting (model memorizes training data)
Optimal depth balances accuracy and generalization

2. Which criterion (gini or entropy) produced the best performance?
Entropy often gives slightly better performance
It uses information gain, leading to better splits
However, difference between gini and entropy is usually small

3. Which Iris class is most frequently misclassified according to the confusion matrix?
Versicolor is most frequently misclassified
Reason: Feature overlap with Virginica

4. What are the advantages and limitations of using Decision Trees for multiclass classification?
Advantages

Easy to understand and interpret
Handles multiclass classification naturally
No need for feature scaling

Limitations
Prone to overfitting
Sensitive to small changes in data
Can create very complex trees

5. How might overfitting occur in a Decision Tree, and how can you prevent it?
Overfitting occurs when:
Tree grows too deep
Very small min_samples_split
Model memorizes noise

Prevention methods:
Limit max_depth
Increase min_samples_split
Pruning
Use ensemble methods (Random Forest)