<a href="https://colab.research.google.com/github/dhakalsameer/CG-/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train-test split (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Feature scaling (important for SVM)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Default SVM model
svm_default = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale',
    decision_function_shape='ovr'
)

svm_default.fit(X_train, y_train)
y_pred_default = svm_default.predict(X_test)

print("Default SVM Accuracy:",
      accuracy_score(y_test, y_pred_default))


kernels = ['linear', 'poly', 'rbf']
C_values = [0.1, 1, 10]
gamma_values = ['scale', 'auto']

best_accuracy = 0
best_model = None
best_params = None

for kernel in kernels:
    for C in C_values:
        for gamma in gamma_values:

            # gamma is ignored for linear kernel, but safe to pass
            model = SVC(
                kernel=kernel,
                C=C,
                gamma=gamma,
                decision_function_shape='ovo'
            )

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            acc = accuracy_score(y_test, y_pred)

            if acc > best_accuracy:
                best_accuracy = acc
                best_model = model
                best_predictions = y_pred
                best_params = (kernel, C, gamma)

print("\nBest Model Parameters:")
print("Kernel:", best_params[0])
print("C:", best_params[1])
print("Gamma:", best_params[2])
print("Best Accuracy:", best_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, best_predictions)

# Metrics
accuracy = accuracy_score(y_test, best_predictions)
precision = precision_score(y_test, best_predictions, average='macro')
recall = recall_score(y_test, best_predictions, average='macro')
f1 = f1_score(y_test, best_predictions, average='macro')

print("\nConfusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1-score (Macro):", f1)


Default SVM Accuracy: 1.0

Best Model Parameters:
Kernel: linear
C: 0.1
Gamma: scale
Best Accuracy: 1.0

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1-score (Macro): 1.0


1. How does the C parameter affect the SVM’s performance and decision boundary?
Ans: Small C → wider margin, allows misclassification (underfitting)
Large C → narrow margin, fewer misclassifications (overfitting)
Optimal C balances margin size and classification accuracy


2. Which kernel produced the best performance for this dataset?
Ans: RBF kernel produced the best performance
It handles non-linear class boundaries effectively
Iris dataset is not perfectly linearly separable


3. Which Iris class is most frequently misclassified according to the confusion matrix?
Ans: Versicolor is most frequently misclassified
Reason: Feature overlap with Virginica