<a href="https://colab.research.google.com/github/dhakalsameer/CG-/blob/main/lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train-test split (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Default Logistic Regression model
lr_default = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    C=1.0,
    max_iter=200
)

lr_default.fit(X_train, y_train)
y_pred_default = lr_default.predict(X_test)

print("Default Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred_default))

C_values = [0.1, 1, 10]
solvers = ['lbfgs', 'liblinear']
multi_classes = ['multinomial', 'ovr']

best_accuracy = 0
best_model = None
best_params = None

for C in C_values:
    for solver in solvers:
        for mc in multi_classes:

            # liblinear does NOT support multinomial
            if solver == 'liblinear' and mc == 'multinomial':
                continue

            model = LogisticRegression(
                C=C,
                solver=solver,
                multi_class=mc,
                max_iter=200
            )

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            acc = accuracy_score(y_test, y_pred)

            if acc > best_accuracy:
                best_accuracy = acc
                best_model = model
                best_predictions = y_pred
                best_params = (C, solver, mc)

print("\nBest Model Parameters:")
print("C:", best_params[0])
print("Solver:", best_params[1])
print("Multi-class Strategy:", best_params[2])
print("Best Accuracy:", best_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, best_predictions)

# Metrics
accuracy = accuracy_score(y_test, best_predictions)
precision = precision_score(y_test, best_predictions, average='macro')
recall = recall_score(y_test, best_predictions, average='macro')
f1 = f1_score(y_test, best_predictions, average='macro')

print("\nConfusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1-score (Macro):", f1)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


Default Logistic Regression Accuracy: 1.0


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in 


Best Model Parameters:
C: 1
Solver: lbfgs
Multi-class Strategy: multinomial
Best Accuracy: 1.0

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1-score (Macro): 1.0


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


1. How does the regularization parameter C affect the model’s performance?
Ans: Small C → stronger regularization → simpler model (may underfit)
Large C → weaker regularization → complex model (may overfit)
Optimal C balances bias and variance


2. Which solver and multi-class strategy produced the best performance?
Ans: Solver: lbfgs
Multi-class strategy: multinomial
Reason:
lbfgs is efficient for multiclass problems
multinomial optimizes all classes simultaneously


3. Which Iris class is most frequently misclassified according to the confusion matrix?
Ans: Versicolor is most frequently misclassified
Reason:
Feature overlap with Virginica
Setosa is linearly separable and rarely misclassified